version: '3'
services:
  # api:
  #   container_name: api
  #   build: ./docker/fastapi
  #   ports:
  #     - "2121:8000"
  #   restart: always

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always